# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle Test2

on:
  workflow_dispatch:
    inputs:
      testSuite:
        description: 'Test Suite'
        required: true
        default: 'RegressionSuite'
      testClass:
        description: 'TEST CLASS'
     

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: 
          chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
   
  
    - name: SonarCloud Scan
      uses:  SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GI_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_KEY }}
        
    - name: Run Tests
      run:
        echo "Log level:${{github.event.inputs.testSuite}}"
        ./gradlew test --info # Run our tests using Gradle
